### ISSUE TITLE
Cannot unpack dailies

### ISSUE THREAD

**Issue by louzhang** [thepanacealab/covid19_twitter#1]
Hello! I'm trying to unpack daily `.tar.gz` files but running into the following error in Python: 

```python
import tar
t = tarfile.open('./covid19_twitter/dailies/2020-03-23/2020-03-23_clean.tar.gz')
```
![Screen Shot 2020-03-25 at 12 19 35 AM](https://user-images.githubusercontent.com/7862691/77511566-92488a80-6e2e-11ea-8c12-4d91877d85fd.png)

And bash: 

```bash
$ tar tvf ./covid19_twitter/dailies/2020-03-23/2020-03-23_clean.tar.gz
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Anyhow, really like your team's work & thanks in advance!

**Comment by jmbanda** [comment]
Sorry for the late response, we did not see this post until now. Can you try again? we have re-updated some of those files.

**Comment by bhashithe** [comment]
This is because its not a `tar archive`. You should be able to unzip the file with `gunzip`, should come with any linux distribution.

**Comment by duhaime** [comment]
@jmbanda some of these .tar.gz archives are still corrupt. Can you try to reexport? 

As @bhashithe notes, the .gz files work well, and can be gunzipped easily. Maybe it makes sense to export all of these as plain .gz archives?

**Comment by duhaime** [comment]
Here's an example .tar.gz file that can't be unpacked: https://github.com/thepanacealab/covid19_twitter/blob/master/dailies/2020-03-22/2020-03-22.tar.gz

**Comment by bhashithe** [comment]
@duhaime Thanks for pointing that out. I have tested 2020-03-22.tar.gz with `tar, unzip, gunzip` which seems to not work. And I agree with you, everything in the same format makes sense.

**Comment by jmbanda** [comment]
Hello, get version 2 or 3 from Zenodo and those dailies are included with the full dataset. Unfortunately, those first dailies were uploaded using LFS on GitHub and for some weird reason you can't pull them normally. I believe if you install LFS  on your local copy of the repo this will work. Also, if you download them from Github.com they are not corrupted, as I just downloaded them in chrome and they unpack properly (I have tried with WinRar).

**Comment by jmbanda** [comment]
Ok, I have removed the old tar files, replaced them with gziped files (as the rest of the dailies). Thanks for pointing out this issue.
