### ISSUE TITLE
"dailies/2020-12-20" and "dailies/2020-12-21" only include the cleaned dataset

### ISSUE THREAD

**Issue by liviucotfas** [thepanacealab/covid19_twitter#12]
Thank you very much for making available the COVID-19 Twitter dataset. While browsing the repository I have noticed that the folders for the dates "2020-12-20" and "2020-12-21" do not include the "dataset.tsv.gz" file. Only the "clean-dataset.tsv.gz" file is included. Would it be possible to add the full dataset files?

**Comment by jmbanda** [comment]
Greetings, thanks for finding this issue. We have added the missing files.
