### ISSUE TITLE
Filter by language. Especially for English

### ISSUE THREAD

**Issue by cagri32** [thepanacealab/covid19_twitter#17]
Hi,

  This is awesome work and I can see how huge effort it must have taken. I am really glad about that. 
  We will use this dataset for our Information Networks course and I was wondering if you have the data in language filtered format. When it comes to filtering it ourselves, we will have to hydrate 1.5 billion tweets only to find the 600 million that are in English. Considering the limitations of our Twitter API access, it will be a huge burden on us.
  Is there any chance you do that for maybe only the English language? I believe you store them non-dehydrated in JSON format.
  That would be a huge help and I believe data in English would be used by a wider community since the tech and research world is mostly work in English.
  Thanks

**Comment by jmbanda** [comment]
Hey there. Thanks for using our dataset. If you see the zenodo repository,
you can see that we include the language tag in each tweet id. This way you
can filter them ID hydrating them. This way you can do analyses on any
language easily.

**Comment by cagri32** [comment]
Hi,
Thank you for responding so quick. I believe I found about this project with an older version of it and the I looked up a date in the dailies folder that has one of the old versions where no location and language data are included . That's why I bothered you. My bad :)
Thanks again
