### ISSUE TITLE
Clustering data

### ISSUE THREAD

**Issue by zadz369d** [thepanacealab/covid19_twitter#20]
Hello,
could you share please the code for clustering data by frequency terms?

Best regards,
Zarnigor.

**Comment by jmbanda** [comment]
Greetings,

The code to generate the  n-grams and 1-grams (single terms) can be found in: https://github.com/thepanacealab/covid19_twitter/tree/master/processing_code

We don't do any 'clustering' in this repository, just generate counts per day, then aggregate them (code for this is also found above).
