### ISSUE TITLE
hello, i failed when i use the parse_json_extreme.py

### ISSUE THREAD

**Issue by pppfl-y** [thepanacealab/covid19_twitter#3]
I run the  "parse_json_extreme.py" in the shall after i download the dataset.tsv ,  but what i get after that was a empty file. i search on google, and found there are something wrong  When the program runs to tweet = json.loads(line)， it always  failed and continue. Am i forgot something ? i didn't know programming and python too much and i'm confused. Can you help me?

when i run the program , what i typed is "python .\parse_json_extreme.py .\2020-03-22-dataset.tsv"

**Comment by jmbanda** [comment]
Greetings, the dataset needs to be hydrated before you can extract anything from the tweet json files. In other words, you need to hydrate the 2020-03-22-dataset.tsv file and this will give you a .json file that you can then use parse_json_extreme.py on.

**Comment by akuma527** [comment]
> Greetings, the dataset needs to be hydrated before you can extract anything from the tweet json files. In other words, you need to hydrate the 2020-03-22-dataset.tsv file and this will give you a .json file that you can then use parse_json_extreme.py on.

Hi @jmbanda , what exactly do you mean by hydration? I looked it up and it says, "filling an object with data". Is there a way to retrieve tweet text and other details quickly?

**Comment by jmbanda** [comment]
Greetings, I would advise you read a bit on how to work with Twitter datasets. Due to their terms and conditions of sharing data, researchers cannot usually share the full Tweet objects (including the text) freely on the internet. So the next best thing is to hydrate an existing dataset. You can find more details on how to do this in this page: https://programminghistorian.org/en/lessons/beginners-guide-to-twitter-data#hydrating

**Comment by akuma527** [comment]
> Greetings, I would advise you read a bit on how to work with Twitter datasets. Due to their terms and conditions of sharing data, researchers cannot usually share the full Tweet objects (including the text) freely on the internet. So the next best thing is to hydrate an existing dataset. You can find more details on how to do this in this page: https://programminghistorian.org/en/lessons/beginners-guide-to-twitter-data#hydrating

This is what I needed! Thanks a ton mate. :)
