### ISSUE TITLE
Link to dataset on Zenodo is broken

### ISSUE THREAD

**Issue by jcatanza** [thepanacealab/covid19_twitter#5]
Readme in version1.0 says:

"Apparently github has a bandwidth limit on free accounts for large files, so the full dataset Version 1 will be available in Zenodo: https://doi.org/10.5281/zenodo.3723940"

But this link to the data set in Zenodo throws an
`Internal server error`, with
`Error identifier: 9eb9e7c76b9348b797b692c529dc143a`

**Comment by jmbanda** [comment]
Greetings, Zenodo in general seems to be down at the moment. Once it comes back up, go to the general link for the dataset: https://doi.org/10.5281/zenodo.3723939 and on the right side you can get any of the 11 released versions.

**Comment by jcatanza** [comment]
Thanks, Juan.
