### ISSUE TITLE
Only Tweet IDs

### ISSUE THREAD

**Issue by akuma527** [thepanacealab/covid19_twitter#9]
Hi,
Once I load the tsv file I can only find 3 columns. Is this correct or are there other columns as well?

**Comment by jecs89** [comment]
Akum, there are twitter limitations. It is not possible to share tweets directly.

**Comment by jmbanda** [comment]
That is correct, we can only share the identifiers and very minimal information from them (date captured, etc.), thanks @jecs89!

**Comment by akuma527** [comment]
> That is correct, we can only share the identifiers and very minimal information from them (date captured, etc.), thanks @jecs89!

Hi @jmbanda, how much time does it take to fetch tweets using these IDs, for example, it takes almost 1 hour to fetch 10,000 tweet ids and get their corresponding data. This the code I'm using:
`def get_tweet_details(id_of_tweet):
    try:
        tweet = api.get_status(id_of_tweet, tweet_mode='extended')
        return tweet
    except Exception:
        return None

df['tweet_id'].apply(get_tweet_details)`
